title: Dina Mahmoud
logo: Images/personal_photo.png
description: Data Analyst with a strong foundation in bioinformatics and expertise in data analysis and visualization using Python, and SQL. Skilled in leveraging tools such as Excel, Power BI, and Tableau to deliver actionable insights and improve business decision-making.
theme: jekyll-theme-minimal
